# Generated by Django 5.1.15 on 2026-04-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'timestamp']},
        ),
    ]
